name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
          with:
            version: 6.10.0
        - name: Setup node env
          uses: actions/setup-node@v3
          with:
            node-version: 16
            check-latest: true
            cache: "pnpm"
        - name: Install dependencies
          run: pnpm install
        - name: Test
          run: pnpm run test
        